version: 2

jobs:
  8.8-tinfo6:
    docker:
      - image: debian:sid
    environment:
      BRANCH: asterius-8.8
      DEBIAN_FRONTEND: noninteractive
      XZ_OPT: -9
    steps:
      - run:
          name: Install dependencies
          command: |
            echo 'deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/20200224T000000Z sid main contrib non-free' > /etc/apt/sources.list
            apt update
            apt full-upgrade -y
            apt install -y \
              automake \
              build-essential \
              curl \
              gawk \
              git \
              libffi-dev \
              libgmp-dev \
              libncurses-dev \
              libnuma-dev \
              libtool-bin \
              pkg-config \
              python3-sphinx \
              xz-utils \
              zlib1g-dev
            mkdir -p ~/.local/bin
            curl -L https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
            ~/.local/bin/stack --resolver nightly-2020-03-14 --no-terminal install \
              alex \
              happy \
              hscolour
      - run:
          name: Initialize ghc repo
          command: |
            cd /tmp
            git clone --recurse-submodules --branch $BRANCH --depth=1 https://github.com/TerrorJack/ghc.git
      - checkout
      - run:
          name: Compile GHC
          no_output_timeout: 1h
          command: |
            export PATH=~/.local/bin:$(~/.local/bin/stack path --compiler-bin):$PATH
            mv .circleci/build.mk /tmp/ghc/mk/
            cd /tmp/ghc
            ./boot
            ./configure
            make
            make binary-dist
            mkdir /tmp/ghc-bindist
            mv *.tar.* /tmp/ghc-bindist/
            (ls -l /tmp/ghc-bindist && sha256sum -b /tmp/ghc-bindist/*) > /tmp/ghc-bindist/sha256.txt
      - store_artifacts:
          path: /tmp/ghc-bindist

  8.8-standard:
    docker:
      - image: debian:stretch
    environment:
      BRANCH: asterius-8.8
      DEBIAN_FRONTEND: noninteractive
      XZ_OPT: -9
    steps:
      - run:
          name: Install dependencies
          command: |
            echo 'deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/20200224T000000Z stretch main contrib non-free' > /etc/apt/sources.list
            echo 'deb [check-valid-until=no] http://snapshot.debian.org/archive/debian-security/20200224T000000Z stretch/updates main contrib non-free' >> /etc/apt/sources.list
            echo 'deb [check-valid-until=no] http://snapshot.debian.org/archive/debian/20200224T000000Z stretch-updates main contrib non-free' >> /etc/apt/sources.list
            apt update
            apt full-upgrade -y
            apt install -y \
              automake \
              build-essential \
              curl \
              gawk \
              git \
              libffi-dev \
              libgmp-dev \
              libncurses-dev \
              libnuma-dev \
              libtool-bin \
              pkg-config \
              python3-sphinx \
              xz-utils \
              zlib1g-dev
            mkdir -p ~/.local/bin
            curl -L https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
            ~/.local/bin/stack --resolver nightly-2020-03-14 --no-terminal install \
              alex \
              happy \
              hscolour
      - run:
          name: Initialize ghc repo
          command: |
            cd /tmp
            git clone --recurse-submodules --branch $BRANCH --depth=1 https://github.com/TerrorJack/ghc.git
      - checkout
      - run:
          name: Compile GHC
          no_output_timeout: 1h
          command: |
            export PATH=~/.local/bin:$(~/.local/bin/stack path --compiler-bin):$PATH
            mv .circleci/build.mk /tmp/ghc/mk/
            cd /tmp/ghc
            ./boot
            ./configure
            make
            make binary-dist
            mkdir /tmp/ghc-bindist
            mv *.tar.* /tmp/ghc-bindist/
            (ls -l /tmp/ghc-bindist && sha256sum -b /tmp/ghc-bindist/*) > /tmp/ghc-bindist/sha256.txt
      - store_artifacts:
          path: /tmp/ghc-bindist

  8.8-musl:
    docker:
      - image: alpine:edge
    environment:
      BRANCH: asterius-8.8
      XZ_OPT: -9
    steps:
      - run:
          name: Install dependencies
          command: |
            echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
            apk update --no-progress
            apk upgrade --no-progress
            apk add --no-progress \
              autoconf \
              automake \
              binutils-gold \
              bzip2 \
              coreutils \
              curl \
              file \
              findutils \
              g++ \
              gawk \
              ghc \
              git \
              gzip \
              libtool \
              musl-dev \
              ncurses-dev \
              numactl-dev \
              openssh \
              patch \
              py3-sphinx \
              sed \
              tar \
              xz \
              zlib-dev
            mkdir -p ~/.local/bin
            curl -L https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-linux-x86_64-static.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
            ~/.local/bin/stack --resolver lts-14.27 --no-terminal --system-ghc install \
              alex \
              happy \
              hscolour
      - run:
          name: Initialize ghc repo
          command: |
            cd /tmp
            git clone --recurse-submodules --branch $BRANCH --depth=1 https://github.com/TerrorJack/ghc.git
      - checkout
      - run:
          name: Compile GHC
          no_output_timeout: 1h
          command: |
            export PATH=~/.local/bin:$PATH
            mv .circleci/build.mk /tmp/ghc/mk/
            cd /tmp/ghc
            ./boot
            ./configure --disable-ld-override
            make
            make binary-dist
            mkdir /tmp/ghc-bindist
            mv *.tar.* /tmp/ghc-bindist/
            (ls -l /tmp/ghc-bindist && sha256sum -b /tmp/ghc-bindist/*) > /tmp/ghc-bindist/sha256.txt
      - store_artifacts:
          path: /tmp/ghc-bindist

  8.8-macos:
    macos:
      xcode: "11.4.0"
    environment:
      BRANCH: asterius-8.8
      JOBS: 4
      XZ_OPT: -9
    steps:
      - run:
          name: Install dependencies
          command: |
            brew update
            brew upgrade
            brew install \
              coreutils \
              gnu-tar \
              sphinx-doc
            mkdir -p ~/.local/bin
            curl -L https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-osx-x86_64.tar.gz | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
            ~/.local/bin/stack --resolver nightly-2020-03-14 --no-terminal install \
              alex \
              happy \
              hscolour
      - run:
          name: Initialize ghc repo
          command: |
            cd /tmp
            git clone --recurse-submodules --branch $BRANCH --depth=1 https://github.com/TerrorJack/ghc.git
      - checkout
      - run:
          name: Compile GHC
          no_output_timeout: 1h
          command: |
            export PATH=~/.local/bin:$(~/.local/bin/stack path --compiler-bin):/usr/local/opt/sphinx-doc/bin:$PATH
            mv .circleci/build-macos.mk /tmp/ghc/mk/build.mk
            cd /tmp/ghc
            ./boot
            ./configure
            make -j$JOBS
            make binary-dist
            mkdir /tmp/ghc-bindist
            mv *.tar.* /tmp/ghc-bindist/
            (ls -l /tmp/ghc-bindist && sha256sum -b /tmp/ghc-bindist/*) > /tmp/ghc-bindist/sha256.txt
      - store_artifacts:
          path: /tmp/ghc-bindist

workflows:
  version: 2
  build:
    jobs:
      - 8.8-tinfo6
      - 8.8-standard
      - 8.8-musl
      - 8.8-macos
