steps:
  - label: "Build it and test it"
    command: |
      docker info
      docker ps -as
      docker images
      docker pull debian:sid
      docker run \
        -it \
        --rm \
        --network host \
        -v $(pwd):/workspaces/asterius \
        -w /workspaces/asterius \
        debian:sid \
        .buildkite/build.sh
