steps:

  - label: "Build it"
    command: |
      docker build \
        --compress \
        --file dev.Dockerfile \
        --force-rm \
        --network host \
        --no-cache \
        --pull \
        --squash \
        --tag asterius:dev \
        .

  - label: "Test it"
    command: |
      docker pull debian:sid
      docker run \
        -it \
        --rm \
        --network host \
        -v $(pwd):/workspaces/asterius \
        -w /workspaces/asterius \
        debian:sid \
        .buildkite/build.sh
