steps:
  - label: "Build dev image"
    command: |
      docker run \
        -it \
        --rm \
        --network host \
        -v $(pwd):/workspaces/asterius \
        -w /workspaces/asterius \
        terrorjack/asterius:dev \
        .devcontainer/build.sh
