steps:
  - label: "Build dev image"
    command: |
      docker build \
        --compress \
        --file dev.Dockerfile \
        --network host \
        --no-cache \
        --pull \
        --tag asterius:dev \
        .
      docker run \
        -it \
        --rm \
        --network host \
        -v $(pwd):/workspaces/asterius \
        -w /workspaces/asterius \
        .devcontainer/build.sh
